chore: migrate back to yarn

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,10 +36,8 @@ jobs:
           fetch-depth: 0
           fetch-tags: true
 
-      - name: Install bun
-        uses: oven-sh/setup-bun@v2
-        with:
-          bun-version: latest
+      - name: Enable Corepack
+        run: corepack enable
 
       - uses: actions/setup-node@v6
         with:
@@ -55,12 +53,13 @@ jobs:
             echo "No git tags found"
             exit 1
           fi
+
       - name: Install Dependencies
-        run: bun install --frozen-lockfile
+        run: yarn install --immutable
 
       - name: New version (dry run)
         if: github.ref == 'refs/heads/main' && inputs.dry-run
-        run: bun run pob-version --dry-run --bump-dependents-highest-as=${{ inputs.bump-dependents-highest-as }}
+        run: yarn run pob-version --dry-run --bump-dependents-highest-as=${{ inputs.bump-dependents-highest-as }}
 
       - name: Configure Git user
         if: github.ref == 'refs/heads/main' && !inputs.dry-run
@@ -71,9 +70,21 @@ jobs:
       - name: New version
         if: github.ref == 'refs/heads/main' && !inputs.dry-run
         run: |
-          npm install -g npm@latest
-          bun run pob-version --publish --create-release=github  --bump-dependents-highest-as=${{ inputs.bump-dependents-highest-as }} -m 'chore: release [skip ci]\n\n%t'
+          yarn run pob-version --create-release=github  --bump-dependents-highest-as=${{ inputs.bump-dependents-highest-as }} -m 'chore: release [skip ci]\n\n%t'
         env:
           POB_GIT_HOOKS: 0
           YARN_ENABLE_IMMUTABLE_INSTALLS: false
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Publish to npm
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
+        run: |
+          if [ -z "$NPM_AUTH_TOKEN" ]; then
+            echo "Missing env variable NPM_AUTH_TOKEN"
+            exit 1
+          fi
+          echo >> ./.yarnrc.yml
+          echo "npmAuthToken: $NPM_AUTH_TOKEN" >> ./.yarnrc.yml
+          yarn workspaces foreach --all --parallel --no-private npm publish --tolerate-republish
+        env:
+          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
